### ISSUE TITLE
Search results pagination problem

### ISSUE THREAD

**Issue by guidokritz** [not-only-code/qtranslate-slug#1]
Search results pagination is not working with the plugin activated.

I get a link with the following format: http://my-site.com/page/2/?s=search+terms
But when I access that URL it shows my home page instead of the search results. It works fine with QTranslage Slug plugin disabled.

Would be great to find a fix for this issue.

EDIT: actually it doesn't show my home page but the page 2 of my blog. Looks like the pagination is working but is ignoring the ?s= parameter and showing the blog instead of the search results.

**Comment by not-only-code** [comment]
Looks like some bug on parse query, i'll check this for next release.
Thanks for report!

**Comment by nikolov-tmw** [comment]
I worked around this bug by replacing line 775 in qtranslate-slug.php, which looks like:
`if (isset($wp->matched_query))`
with:
`if ( isset( $wp->matched_query ) && ! isset( $query['s'] ) )`

What I found was, that `$wp->matched_query` was `&paged=2` when it should have been `s=s&paged=2`. I'm not sure what is the reason for that, but this should do as a workaround for now :)

**Comment by not-only-code** [comment]
Something in **query_vars** function is wrong that's because i've used this kind of _hacks_ at beginning of **filter_request** function. May have to do with **generate_rewrite_rules** are builded or maybe it is produced by this issue https://github.com/not-only-code/qtranslate-slug/issues/31.
I must to check this.

Thanks for report.

**Comment by not-only-code** [comment]
This has been is solved with [#31](https://github.com/not-only-code/qtranslate-slug/issues/31). Anyway i just opened another issue to rewrite the _hacks_ at beginnig of **filter_request** funciton (https://github.com/not-only-code/qtranslate-slug/issues/36)

**Comment by evpozdniakov** [comment]
The fix #31 didn't solve the problem. But it stated working for me after adding 

```
 && ! isset( $query['s'] )
```

(as nikolov-tmw recomended)

**Comment by not-only-code** [comment]
This patch https://github.com/not-only-code/qtranslate-slug/commit/4d6864f64c38d53bf928257abbf96185b9af713e should solve this, so i close this issue. Anyway is pending rewrite form scratch **filter_request** function as #36 says.
